openapi: "3.0.1"
info:
  title: "Asistencia API"
  version: "1.0"

paths:
  /asistencias:
    get:
      summary: "Consultar asistencia"
      parameters:
        - name: "alumnoID"
          in: "path"
          required: true
          schema:
            type: string
        - name: "fechaDesde"
          in: "path"
          required: false
          schema:
            type: string
        - name: "fechaHasta"
          in: "path"
          required: false
          schema:
            type: string
      responses:
        "200":
          description: "OK"
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri: arn:aws:apigateway:mx-central-1:lambda:path/2015-03-31/functions/${lambda_asistencia_arn}/invocations

    post:
      summary: "Crear asistencia"
      responses:
        "200":
          description: "OK"
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri: arn:aws:apigateway:mx-central-1:lambda:path/2015-03-31/functions/${lambda_asistencia_arn}/invocations

  /asistencias/alumno/{alumnoID}:
    get:
      summary: "Obtener asistencia por ID"
      parameters:
        - name: "alumnoID"
          in: "path"
          required: true
          schema:
            type: string
        - name: "fecha_desde"
          in: "path"
          required: false
          schema:
            type: string
        - name: "fecha_hasta"
          in: "path"
          required: false
          schema:
            type: string
      responses:
        "200":
          description: "OK"
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri: arn:aws:apigateway:mx-central-1:lambda:path/2015-03-31/functions/${lambda_asistencia_arn}/invocations

    put:
      summary: "Actualizar asistencia"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "OK"
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri: arn:aws:apigateway:mx-central-1:lambda:path/2015-03-31/functions/${lambda_asistencia_arn}/invocations

    delete:
      summary: "Borrar asistencia"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "OK"
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri: arn:aws:apigateway:mx-central-1:lambda:path/2015-03-31/functions/${lambda_asistencia_arn}/invocations

  /asistencias/escuela/{escuelaID}:
    get:
      summary: "Obtener asistencia por ID"
      parameters:
        - name: "escuelaID"
          in: "path"
          required: true
          schema:
            type: string
        - name: "fecha_desde"
          in: "path"
          required: false
          schema:
            type: string
        - name: "fecha_hasta"
          in: "path"
          required: false
          schema:
            type: string
      responses:
        "200":
          description: "OK"
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri: arn:aws:apigateway:mx-central-1:lambda:path/2015-03-31/functions/${lambda_asistencia_arn}/invocations

  /asistencias/grado/{gradoID}:
    get:
      summary: "Obtener asistencia por ID"
      parameters:
        - name: "gradoID"
          in: "path"
          required: true
          schema:
            type: string
        - name: "fecha_desde"
          in: "path"
          required: false
          schema:
            type: string
        - name: "fecha_hasta"
          in: "path"
          required: false
          schema:
            type: string
      responses:
        "200":
          description: "OK"
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri: arn:aws:apigateway:mx-central-1:lambda:path/2015-03-31/functions/${lambda_asistencia_arn}/invocations

  /escuelas:
    get:
      summary: "Consultar escuelas"
      responses:
        "200":
          description: "OK"
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri: arn:aws:apigateway:mx-central-1:lambda:path/2015-03-31/functions/${lambda_escuela_arn}/invocations

    post:
      summary: "Crear escuelas"
      responses:
        "200":
          description: "OK"
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri: arn:aws:apigateway:mx-central-1:lambda:path/2015-03-31/functions/${lambda_escuela_arn}/invocations

  /escuelas/{id}:
    get:
      summary: "Obtener escuela por ID"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "OK"
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri: arn:aws:apigateway:mx-central-1:lambda:path/2015-03-31/functions/${lambda_escuela_arn}/invocations

    put:
      summary: "Actualizar escuela"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "OK"
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri: arn:aws:apigateway:mx-central-1:lambda:path/2015-03-31/functions/${lambda_escuela_arn}/invocations

    delete:
      summary: "Borrar escuela"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "OK"
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri: arn:aws:apigateway:mx-central-1:lambda:path/2015-03-31/functions/${lambda_escuela_arn}/invocations

  /maestros:
    get:
      summary: "Consultar maestros"
      responses:
        "200":
          description: "OK"
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri: arn:aws:apigateway:mx-central-1:lambda:path/2015-03-31/functions/${lambda_maestros_arn}/invocations

    post:
      summary: "Crear maestros"
      responses:
        "200":
          description: "OK"
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri: arn:aws:apigateway:mx-central-1:lambda:path/2015-03-31/functions/${lambda_maestros_arn}/invocations

  /maestros/{id}:
    get:
      summary: "Obtener maestros por ID"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "OK"
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri: arn:aws:apigateway:mx-central-1:lambda:path/2015-03-31/functions/${lambda_maestros_arn}/invocations

    put:
      summary: "Actualizar maestro"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "OK"
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri: arn:aws:apigateway:mx-central-1:lambda:path/2015-03-31/functions/${lambda_maestros_arn}/invocations

    delete:
      summary: "Borrar maestro"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "OK"
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri: arn:aws:apigateway:mx-central-1:lambda:path/2015-03-31/functions/${lambda_maestros_arn}/invocations

  /alumnos:
    get:
      summary: "Consultar alumnos"
      responses:
        "200":
          description: "OK"
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri: arn:aws:apigateway:mx-central-1:lambda:path/2015-03-31/functions/${lambda_alumnos_arn}/invocations

    post:
      summary: "Crear alumnos"
      responses:
        "200":
          description: "OK"
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri: arn:aws:apigateway:mx-central-1:lambda:path/2015-03-31/functions/${lambda_alumnos_arn}/invocations

  /alumnos/{id}:
    get:
      summary: "Obtener alumnos por ID"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "OK"
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri: arn:aws:apigateway:mx-central-1:lambda:path/2015-03-31/functions/${lambda_alumnos_arn}/invocations

    put:
      summary: "Actualizar alumnos"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "OK"
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri: arn:aws:apigateway:mx-central-1:lambda:path/2015-03-31/functions/${lambda_alumnos_arn}/invocations

    delete:
      summary: "Borrar alumnos"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "OK"
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri: arn:aws:apigateway:mx-central-1:lambda:path/2015-03-31/functions/${lambda_alumnos_arn}/invocations

  /tutores:
    get:
      summary: "Consultar tutores"
      responses:
        "200":
          description: "OK"
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri: arn:aws:apigateway:mx-central-1:lambda:path/2015-03-31/functions/${lambda_tutores_arn}/invocations

    post:
      summary: "Crear tutor"
      responses:
        "200":
          description: "OK"
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri: arn:aws:apigateway:mx-central-1:lambda:path/2015-03-31/functions/${lambda_tutores_arn}/invocations

  /tutores/{id}:
    get:
      summary: "Obtener tutor por ID"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "OK"
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri: arn:aws:apigateway:mx-central-1:lambda:path/2015-03-31/functions/${lambda_tutores_arn}/invocations

    put:
      summary: "Actualizar tutor"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "OK"
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri: arn:aws:apigateway:mx-central-1:lambda:path/2015-03-31/functions/${lambda_tutores_arn}/invocations

    delete:
      summary: "Borrar tutor"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "OK"
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri: arn:aws:apigateway:mx-central-1:lambda:path/2015-03-31/functions/${lambda_tutores_arn}/invocations

  /grados:
    get:
      summary: "Consultar grados"
      responses:
        "200":
          description: "OK"
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri: arn:aws:apigateway:mx-central-1:lambda:path/2015-03-31/functions/${lambda_grados_arn}/invocations

    post:
      summary: "Crear grado"
      responses:
        "200":
          description: "OK"
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri: arn:aws:apigateway:mx-central-1:lambda:path/2015-03-31/functions/${lambda_grados_arn}/invocations

  /grados/{id}:
    get:
      summary: "Obtener grado por ID"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "OK"
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri: arn:aws:apigateway:mx-central-1:lambda:path/2015-03-31/functions/${lambda_grados_arn}/invocations

    put:
      summary: "Actualizar grado"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "OK"
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri: arn:aws:apigateway:mx-central-1:lambda:path/2015-03-31/functions/${lambda_grados_arn}/invocations

    delete:
      summary: "Borrar grado"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "OK"
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri: arn:aws:apigateway:mx-central-1:lambda:path/2015-03-31/functions/${lambda_grados_arn}/invocations
